first version of PSO algorithm is done
ormequ/particle_swarm_optimization pull request #1
Opened 2023-07-02 18:43 UTC by MuhachevaPolina

2023-07-02 20:05 UTC, ormequ requested changes

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +class Plane_Function:
Классы нужно именовать в PascalCase

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +        self.weight2 = weight2
Переименовать local_weight, global_weight

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +        self.boundaries_y = boundaries_y
boundaries лучше хранить кортежем

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +        присваение минимального значения для каждой частицы
присвоение*

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/particle_swarm_optimiization.py
> +import numpy as np
Думаю, можно оставить только версию с инерцией

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +        присваение минимального значения для каждой частицы
ну или присваивание

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +            self.particles.append(Particle(tmp_pos, tmp_vel))
Лучше не tmp_pos, tmp_vel, а start_pos, start_vel

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +        self.particles[index].velocity = self.inertion * cur_particle.velocity + weight1 * np.random.rand(2) * (cur_particle.best_pos - cur_particle.position) + weight2 * np.random.rand(2) * (self.be
Можешь, пожалуйста, разделить эту формулу на 3 части, а потом записать их сумму?

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +            if self.boundaries_y[0] <= new_position[1] and new_position[1] <= self.boundaries_y[1]: # проверка: координаты частицы не вылезли за значение по Y
Вот поэтому я и говорил про кортеж boundaries. Тут был бы цикл

2023-07-02 20:05 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +                # тут, если скорость слишком большая/маленькая, чтобы двигаться дальше, можно точку просто на границу, наверное, ставить
да, в ином случае ставим на ближайшую подходящую границу

2023-07-02 20:09 UTC, ormequ commented
И еще добавь, пожалуйста, типы))
![изображение](https://github.com/ormequ/particle_swarm_optimization/assets/57725831/036d9c85-8acd-42ee-a6dc-3340ed6a79b5)

2023-07-02 20:13 UTC, MuhachevaPolina commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +            if self.boundaries_y[0] <= new_position[1] and new_position[1] <= self.boundaries_y[1]: # проверка: координаты частицы не вылезли за значение по Y
Я не могу понять, какой цикл имеется в виду и почему использование кортежей в данном случае выгоднее. Можешь, пожалуйста, объяснить?

2023-07-02 20:17 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +            if self.boundaries_y[0] <= new_position[1] and new_position[1] <= self.boundaries_y[1]: # проверка: координаты частицы не вылезли за значение по Y
```python
for i in range(len(self.boundaries):
    if self.boundaries[i][0]  > new_position[i] and new_position[i] > self.boundaries[i][1]:
        new_position[i] = self.boundaries[i].copy()
```
Ну или как-то так

2023-07-02 20:19 UTC, ormequ commented on PSO_algorithm_first_ver/inertion_particle_swarm_optimiization.py
> +            if self.boundaries_y[0] <= new_position[1] and new_position[1] <= self.boundaries_y[1]: # проверка: координаты частицы не вылезли за значение по Y
Именно кортеж необязательно. Можно вообще np.array сделать. Так даже лучше будет

2023-07-03 05:35 UTC, ormequ reviewed
Все хорошо, остались только типы)

2023-07-03 06:39 UTC, ormequ approved these changes

2023-07-03 06:40 UTC, merged